#!/usr/bin/env bash

clean () {
  rm -f ${stripped} ${numbered} ${log}
}

# Ensure single, non-empty string argument passed
[ $# -ne 1 -o -z "${1}" ] && { echo "Usage: ${0} <Rexx file>" ; exit 1 ; }

# Input file: Rexx script sans extension
source="${1##*/}" ; source="${source%.*}"

# Temporary files
stripped="${source}.stripped.rexx"
numbered="${source}.numbered.rexx"
log="${source}.log.txt"

# Strip all comments from script
sed -E 's/^\s*(.*)\/\*.*\*\/\s*(.*)/\1\2/g' "${source}.rexx" \
  | sed -E 's/^\s*(.*)\/\*.*\*\/\s*(.*)/\1\2/g' \
  | sed '/\/\*/,/*\//d;/^\s*$/d' > "${stripped}"

# Number the stripped script
cat -n "${stripped}" > "${numbered}"

# Execute script capturing error output
regina -tO "${stripped}" 2> "${log}" 1> /dev/null

# Emit source code for context
cat "${numbered}"

# Remove temporary files
clean

# Assume a syntax error occurred
exit 1
